### ISSUE TITLE
LinkedResources are not supported?

### ISSUE THREAD

**Issue by UDTDR** [fredericdasilva/NetSecureMail#1]
Hello, how I can use embedded images/LinkedResources? 

Thanks

best regards

**Comment by fredericdasilva** [comment]
Hello

You can find a good example here: 
http://www.codeproject.com/KB/IP/emailembeddedimages.aspx

Regards

FD

**Comment by UDTDR** [comment]
Hello, thanks, but I need an example with SMIME (signed mails) and embedded images!

**Comment by fredericdasilva** [comment]
Hello, sorry I tried without sucess.. Please let me know if you find good example on your side.
